apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-storage
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2

# With storage class, persistent volume will be dynamically created 
# therefore i dont need to specify it here.
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ebs-storage
  resources:
    requests:
      storage: 10Gi