apiVersion: apps/v1
kind: Deployment
metadata:
  name: apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apps
  template:
    metadata:
      labels:
        app: apps
    spec:
      containers:
      - name: front-end
        image: jmcglobal/python-app:latest
        ### Referencing environment varibale from configmap
        env:
        - name: DB-Connect-Url
          valueFrom:
            configMapKeyRef:
              name: db-string
              key: database.url
        ports:
          containerPort: 8000